In [11]:
import numpy as numpy
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [15]:
df = pd.read_csv("movies_metadata.csv")

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [17]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [6]:
df.shape

(45466, 24)

In [7]:
df = df.drop_duplicates().reset_index(drop=True)

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df = df[["title", "overview", "genres", "vote_average", "tagline", "popularity"]]

In [10]:
df

,title,overview,genres,vote_average,tagline,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",7.7,NaN,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",6.9,Roll the dice and unleash the excitement!,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",6.5,Still Yelling. Still Fighting. Still Ready for...,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",6.1,Friends are the people who let you be yourself...,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",5.7,Just When His World Is Back To Normal... He's ...,8.387519
...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",4.0,Rising and falling between a man and woman,0.072051
45449,Century of Birthing,An artist struggles to finish his work while a...,"[{'id': 18, 'name': 'Drama'}]",9.0,NaN,0.178241
45450,Betrayal,"When one of her hits goes wrong, a professiona...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",3.8,A deadly game of wits.,0.903007
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",[],0.0,NaN,0.003503
45452,Queerama,50 years after decriminalisation of homosexual...,[],0.0,NaN,0.163015

In [11]:
df = df.dropna(subset=["title"])

In [12]:
df

,title,overview,genres,vote_average,tagline,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",7.7,NaN,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",6.9,Roll the dice and unleash the excitement!,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",6.5,Still Yelling. Still Fighting. Still Ready for...,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",6.1,Friends are the people who let you be yourself...,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",5.7,Just When His World Is Back To Normal... He's ...,8.387519
...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",4.0,Rising and falling between a man and woman,0.072051
45449,Century of Birthing,An artist struggles to finish his work while a...,"[{'id': 18, 'name': 'Drama'}]",9.0,NaN,0.178241
45450,Betrayal,"When one of her hits goes wrong, a professiona...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",3.8,A deadly game of wits.,0.903007
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",[],0.0,NaN,0.003503
45452,Queerama,50 years after decriminalisation of homosexual...,[],0.0,NaN,0.163015

In [13]:
df.isnull().sum()

title               0
overview          954
genres              0
vote_average        0
tagline         25039
popularity          0
dtype: int64

In [14]:
df['overview'] = df['overview'].fillna('')

In [15]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [16]:
import ast

In [17]:
df['genres'] = df['genres'].apply(lambda x: " ".join([i['name'] for i in ast.literal_eval(x)]))

In [18]:
df.head()

,title,overview,genres,vote_average,tagline,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,7.7,NaN,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,6.9,Roll the dice and unleash the excitement!,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,6.5,Still Yelling. Still Fighting. Still Ready for...,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,6.1,Friends are the people who let you be yourself...,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,5.7,Just When His World Is Back To Normal... He's ...,8.387519

In [18]:
df['tagline'] = df['tagline'].fillna('')

In [20]:
df.isnull().sum()

title           0
overview        0
genres          0
vote_average    0
tagline         0
popularity      0
dtype: int64

In [19]:
df["tag"] = df["overview"] + " " + df["genres"] + " " + df["tagline"]

In [22]:
df.head()

,title,overview,genres,vote_average,tagline,popularity,tag
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,7.7,,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,6.9,Roll the dice and unleash the excitement!,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,6.5,Still Yelling. Still Fighting. Still Ready for...,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,6.1,Friends are the people who let you be yourself...,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,5.7,Just When His World Is Back To Normal... He's ...,8.387519,Just when George Banks has recovered from his ...

In [25]:
df['tag'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [2]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [3]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\praba\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\praba\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [4]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [5]:
def preprocess_text(text):
    #lowercase
    text = str(text).lower()
    
    #remove special characters and numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    
    #tokenize
    words = text.split()
    
    #remove stop words
    words = [word for word in words if word not in stop_words]
    
    #lemmatize
    words = [lemmatizer.lemmatize(word) for word in words]
    return " ".join(words)

In [20]:
# Apply preprocessing to the 'tag' column
df['tag'] = df['tag'].apply(preprocess_text)

In [21]:
df['tag'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature id name adventure id name fantasy id name family roll dice unleash excitement'

In [22]:
df = df.reset_index(drop=True)

In [23]:
# Create a mapping of movie titles to their indices
indices = pd.Series(df.index, index=df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45461
Century of Birthing            45462
Betrayal                       45463
Satan Triumphant               45464
Queerama                       45465
Length: 45466, dtype: int64

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [26]:
# Create the TF-IDF vectorizer
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1, 2), stop_words='english')

In [27]:
# Fit and transform the 'tag' column to create the TF-IDF matrix
tfidf_matrix = tfidf.fit_transform(df['tag'])

In [28]:
tfidf_matrix

<45466x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 1262778 stored elements in Compressed Sparse Row format>

In [35]:

from sklearn.metrics.pairwise import cosine_similarity

In [39]:
# Function to recommend movies based on cosine similarity
def recommend(title, n=10):
    if title not in indices:
        return ("Movie not found in the dataset")

    idx = indices[title]
    sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
    similar_idx = sim_score.argsort()[-n-1:-1][::-1]
    return df['title'].iloc[similar_idx]

In [51]:
recommend('Jumanji')

21633                    Table No. 21
3872               Dungeons & Dragons
9503                        Word Wars
44376               Liar Game: Reborn
30250                 The Games Maker
6166                        Brainscan
22751            Knights of Badassdom
19791           Indie Game: The Movie
22911                      Love Games
14710    Asterix at the Olympic Games
Name: title, dtype: object

In [ ]:
# Save the TF-IDF matrix, indices, DataFrame, and TF-IDF vectorizer using pickle
import pickle
pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb'))
pickle.dump(indices, open('indices.pkl', 'wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf, open('tfidf.pkl', 'wb'))